FROM scratch as runner
LABEL maintainer="hedongshu <hedongshu@foxmail.com>"
COPY ./build/markdown-book-linux-amd64/markdown-book /data/app/

EXPOSE 5006

ENTRYPOINT ["/data/app/markdown-book", "web"]
